# 端口
server:
  port: 80

# spring boot基本配置
spring:
  application:
    name: modelform
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modelform?useSSL=false
    username: root
    password: 1234

#thymelea模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
      
    

# redis配置
  redis:
    host: 192.168.121.128
    password: 123456
    database: 0
    pool:
      max-active: 10
      max-wait: 20000
      max-idle: 10
      min-idle: 5

# mybatis配置      
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wy.model.entity

# mybatis分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  
  
logging:
  level:
    org.mybatis: debug
    com.wy.model: debug
    org.springframework.transaction: debug
    org.springframework.web: debug
  
  